package com.jobfinder.main.enums;

public enum Industry {

	
	TECHNOLOGY, 
	HEALTHCARE, 
	FINANCE, 
	EDUCATION, 
	RETAIL,
    MANUFACTURING, 
    TRANSPORTATION, 
    CONSTRUCTION, 
    HOSPITALITY,
    MEDIA_ENTERTAINMENT, 
    LEGAL, 
    ADMINISTRATION,
    REAL_ESTATE, 
    MARKETING_ADVERTISING,
    ENERGY_UTILITIES, 
    AGRICULTURE, 
    PUBLIC_SECTOR, 
    AEROSPACE,
    AUTOMOTIVE, 
    PHARMACEUTICALS, 
    TELECOMMUNICATIONS
}
